# Playground
This notebook has space for playing around with any code.

## Laplacian Matrix

In [3]:
import numpy as np
import networkx as nx

# Make small random graph
g1 = nx.erdos_renyi_graph(5,0.4)
# Add self-loop edges
g1.add_edges_from(zip(range(5),range(5)))

print("Adjacency matrix of graph:")
print(nx.to_numpy_matrix(g1))

print("\nLaplacian computed by networkx:")
print(nx.laplacian_matrix(g1).todense())

# Compute it ourselves
print("\nLaplacian computed ourselves:")
lpmat = np.diag([d[1] for d in g1.degree])-nx.to_numpy_matrix(g1)
print(lpmat)

# Compute D^(-1/2)
dmat = np.power(np.diag([d[1] for d in g1.degree]),-1/2)
dmat[np.isinf(dmat)]=0
print("\nD^(-1/2)")
print(dmat)

# Compute final matrix D^(-1/2)*A*D^(-1/2)
print("\nD^(-1/2)*A*D^(-1/2)")
print(dmat*lpmat*dmat)

print("\nNormalized Laplacian computed by networkx:")
print(np.round(nx.normalized_laplacian_matrix(g1).todense(),2))

print("\nD^(-1/2)*A*D^(-1/2) computed by networkx:")
print(np.round(-nx.normalized_laplacian_matrix(g1).todense()+np.identity(5),4))


Adjacency matrix of graph:
[[1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0.]
 [1. 0. 0. 1. 1.]
 [0. 1. 0. 1. 1.]]

Laplacian computed by networkx:
[[ 1  0  0 -1  0]
 [ 0  2 -1  0 -1]
 [ 0 -1  1  0  0]
 [-1  0  0  2 -1]
 [ 0 -1  0 -1  2]]

Laplacian computed ourselves:
[[ 2.  0.  0. -1.  0.]
 [ 0.  3. -1.  0. -1.]
 [ 0. -1.  2.  0.  0.]
 [-1.  0.  0.  3. -1.]
 [ 0. -1.  0. -1.  3.]]

D^(-1/2)
[[0.57735027 0.         0.         0.         0.        ]
 [0.         0.5        0.         0.         0.        ]
 [0.         0.         0.57735027 0.         0.        ]
 [0.         0.         0.         0.5        0.        ]
 [0.         0.         0.         0.         0.5       ]]

D^(-1/2)*A*D^(-1/2)
[[ 0.66666667  0.          0.         -0.28867513  0.        ]
 [ 0.          0.75       -0.28867513  0.         -0.25      ]
 [ 0.         -0.28867513  0.66666667  0.          0.        ]
 [-0.28867513  0.          0.          0.75       -0.25      ]
 [ 0.         -0.25        0.        